"""corrected table Show columns names.

Revision ID: 74e628ef8f0a
Revises: f141f274cf26
Create Date: 2020-06-24 09:31:35.413566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e628ef8f0a'
down_revision = 'f141f274cf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.drop_column('shows', 'artists_image_link')
    op.drop_column('shows', 'artists_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artists_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artists_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###
